package:
  name: r-cimpl
  version: 1.1
source:
  path: ../
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r
    - 'r-kernsmooth'
    - 'r-mass'
    - 'r-xtable'
    - 'bioconductor-biomart'
    - 'bioconductor-biostrings'
  run:
    - r
    - 'r-kernsmooth'
    - 'r-mass'
    - 'r-xtable'
    - 'bioconductor-biomart'
    - 'bioconductor-biostrings'
test:
  commands:
    - '$R -e "library(''cimpl'')"'
about:
  home: http://ccb.nki.nl/software/
  license: GPL-3
  summary: 'An analysis package for multi sample insertional mutagenesis data
    (including viral- and transposon-based systems) using Gaussian kernel
    convolution to identify common insertion sites.'
